version: '3.4'

services:
  erppos:
    image: erpposa
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 4200:4200
    volumes: 
      - .:/usr/src/app
    environment:
      NODE_ENV: production
